// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Apikey struct {
	Key  string
	Name string
	Uid  sql.NullInt64
}

type Bugreport struct {
	ID        int64
	Problem   string
	Result    string
	Steps     string
	CreatedAt int64
	Uid       int64
}

type Session struct {
	Accesstoken  string
	Refreshtoken string
	Valid        sql.NullInt64
}

type User struct {
	ID         int64
	Username   string
	Password   string
	Email      string
	Reset      sql.NullString
	ResetTime  sql.NullInt64
	Valid      sql.NullInt64
	ValidToken sql.NullString
}
