// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: qa.sql

package database

import (
	"context"
)

const reportBug = `-- name: ReportBug :exec
INSERT INTO bugreports(problem, result, steps, uid, created_at)
VALUES(?, ?, ?, ?, strftime("%s", "now"))
`

type ReportBugParams struct {
	Problem string
	Result  string
	Steps   string
	Uid     int64
}

func (q *Queries) ReportBug(ctx context.Context, arg ReportBugParams) error {
	_, err := q.db.ExecContext(ctx, reportBug,
		arg.Problem,
		arg.Result,
		arg.Steps,
		arg.Uid,
	)
	return err
}
